pipeline {
    agent any
    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    // Use withCredentials to bind DockerHub credentials
                    withCredentials([usernamePassword(credentialsId: '9b02679d-c292-4dfa-8551-69309a6d5880', usernameVariable: 'DOCKERHUB_USERNAME', passwordVariable: 'DOCKERHUB_PASSWORD')]) {
                        // Change directory to 'boltzmann-openmp' where Dockerfile is located
                        dir('boltzmann-openmp') {
                            // Build the Docker image
                            def image = docker.build("crusty97/boltzmann-openmp:${env.BUILD_NUMBER}")

                            // Log in to DockerHub
                            sh "echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_USERNAME} --password-stdin"

                            // Push the Docker image to DockerHub
                            image.push()
                            image.push('latest')

                            // Log out from DockerHub
                            sh 'docker logout'
                        }
                    }
                }
            }
        }
    }
    post {
        success {
            echo 'Build and push were successful!'
        }
        failure {
            echo 'Build or push failed.'
        }
    }
}
